import { Component, OnInit } from '@angular/core';
import { Observable, of } from 'rxjs';

@Component({
  selector: 'app-license-agreement',
  templateUrl: './license-agreement.component.html',
  styleUrls: ['./license-agreement.component.css'],
})
export class LicenseAgreementComponent implements OnInit {
  licenseAgreement: Observable<string> | undefined;
  constructor() {}

  ngOnInit(): void {
    this.licenseAgreement = of(
      `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer turpis erat, aliquet ac dictum eu, ornare vel metus. In hac habitasse platea dictumst. Nunc maximus gravida est non auctor. Sed fermentum, est sed tempus cursus, sapien augue tincidunt lacus, a vulputate lacus metus quis dui. Duis eu malesuada ante. Quisque rutrum iaculis molestie. Vivamus non orci sed magna lacinia ornare ut non ex.
        Duis faucibus elit finibus, ornare dui id, facilisis diam. Morbi convallis tempus magna, vitae auctor est commodo sit amet. Praesent aliquam lacus vitae sem malesuada fringilla. Duis turpis neque, mattis eu vestibulum ac, dapibus sodales ligula. Integer a metus at mi tincidunt consequat. Praesent sit amet dignissim magna. Ut eu justo quis mi mattis cursus. Vestibulum eu libero dictum, consequat sem sit amet, fringilla eros. Duis nec nisl nec nibh pellentesque aliquam. Aenean at elit eu dolor malesuada ultrices at sit amet metus. Fusce ac cursus nisl, at luctus ante. Nulla eget dolor id felis varius suscipit vel eu tortor.
        Duis facilisis accumsan mauris, et tincidunt lacus tincidunt id. Mauris ut sodales felis, eget commodo enim. Mauris sed semper mauris, vitae tristique libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus dignissim, orci nec interdum fermentum, lacus lectus tristique mi, ut venenatis magna nisi id justo. Quisque viverra euismod tincidunt. Duis sollicitudin sem risus, eu pellentesque est auctor non. Aenean maximus pellentesque odio nec pulvinar.
        Proin sed porttitor velit. Aenean vulputate consequat ligula, in semper quam vulputate vitae. Quisque pharetra efficitur placerat. Nunc et pulvinar urna. Ut orci leo, fringilla at mauris nec, congue tincidunt elit. Mauris est orci, laoreet non nisl sit amet, egestas suscipit mauris. Praesent quis tempor lectus. Nulla enim leo, malesuada non volutpat vel, bibendum in ex. Suspendisse pulvinar vitae quam eget malesuada.
        Integer sapien tortor, consectetur sit amet nisi quis, pulvinar vulputate magna. Morbi efficitur fermentum finibus. Phasellus a lacus ante. In sit amet nisl quis dui finibus laoreet non at augue. Nunc vulputate volutpat massa varius eleifend. Pellentesque non odio non mi interdum porttitor. Donec quis metus eu erat faucibus vulputate id ut neque. Vestibulum augue mi, ultrices a porta fringilla, volutpat sit amet nisi. Vivamus at tellus nec erat blandit viverra. Nulla et vulputate lorem. Vivamus pulvinar nisl non nisi venenatis, eu molestie erat mattis. Curabitur a nisl faucibus, luctus neque et, malesuada nisl. Donec convallis, sapien non tristique sodales, nibh augue facilisis urna, in eleifend purus tellus ac quam.
        Mauris finibus, enim ac dapibus tempus, augue augue interdum massa, sed mattis felis tortor id velit. Curabitur luctus egestas sem, tempus interdum dui pharetra id. Mauris scelerisque tortor nulla, eget facilisis erat pulvinar vitae. Aenean condimentum commodo libero. Curabitur eleifend massa sagittis nisi malesuada pellentesque. Maecenas metus enim, porta a ornare vitae, porttitor vel quam. Nunc viverra odio eros, eget elementum nibh finibus sit amet. Pellentesque quis fermentum arcu, id tempor velit. Mauris facilisis gravida odio quis euismod. Donec ultricies sed est eget lacinia. Aliquam tincidunt placerat urna sit amet pellentesque.
        Nullam luctus tortor quis tellus venenatis sodales. Donec vel felis eget mi consectetur efficitur. Etiam aliquam nisi sit amet quam interdum, at iaculis urna scelerisque. Vivamus porta neque arcu, nec pretium magna pellentesque nec. Etiam id aliquet urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum, velit non viverra cursus, felis augue posuere neque, nec posuere dui nisi eleifend velit. Phasellus est urna, viverra eget turpis vel, cursus pretium ex. Curabitur mattis convallis velit, vitae auctor purus imperdiet ut. Sed fringilla feugiat augue, ac consectetur lorem tincidunt quis. Vivamus tincidunt dolor ut laoreet pharetra. Aliquam rhoncus vel odio at lobortis.
        Cras faucibus purus non metus aliquam, sed gravida leo feugiat. Curabitur laoreet malesuada volutpat. Vestibulum faucibus nisl eu elit sodales, in blandit ante suscipit. Quisque tincidunt purus nibh, eu efficitur turpis malesuada in. Vivamus aliquet sagittis dolor, non pulvinar nunc sollicitudin at. Sed tincidunt rutrum mauris, vel consectetur lectus condimentum at. Nulla auctor interdum augue, ac facilisis diam rhoncus ut.
        Cras at fringilla mauris. Donec ac condimentum neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut nec mauris id tortor laoreet posuere. Integer mollis dui vel orci pharetra laoreet. Nam quis ligula a lectus pretium rutrum. Donec vel lorem porta ex malesuada volutpat. Etiam venenatis ex molestie, sodales ante quis, tempus urna. Nunc vulputate at ipsum feugiat aliquet. Sed convallis, nunc eu pretium pretium, ante nulla tempor erat, sit amet dignissim risus magna a quam. Donec a ipsum malesuada lectus lacinia varius eget ac dui. Integer risus libero, vulputate eu elit non, tempus iaculis tellus. Curabitur lobortis vel erat sit amet viverra. Integer consequat, odio rhoncus varius aliquet, tortor nisi sodales urna, vel lobortis mi urna sed erat.
        Mauris commodo nisl ac urna aliquam condimentum. Curabitur enim libero, bibendum ut placerat et, aliquam eu tellus. Sed in feugiat tortor. Phasellus lobortis quam a nibh gravida mollis. Donec sit amet odio convallis, pharetra eros et, maximus nisi. Nam pellentesque dolor ut mattis tempor. Nulla vel porta turpis. Proin sed vulputate est. Nulla facilisi. Nullam odio sapien, feugiat non leo nec, cursus sagittis magna. Proin ac velit turpis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer turpis erat, aliquet ac dictum eu, ornare vel metus. In hac habitasse platea dictumst. Nunc maximus gravida est non auctor. Sed fermentum, est sed tempus cursus, sapien augue tincidunt lacus, a vulputate lacus metus quis dui. Duis eu malesuada ante. Quisque rutrum iaculis molestie. Vivamus non orci sed magna lacinia ornare ut non ex.
        Duis faucibus elit finibus, ornare dui id, facilisis diam. Morbi convallis tempus magna, vitae auctor est commodo sit amet. Praesent aliquam lacus vitae sem malesuada fringilla. Duis turpis neque, mattis eu vestibulum ac, dapibus sodales ligula. Integer a metus at mi tincidunt consequat. Praesent sit amet dignissim magna. Ut eu justo quis mi mattis cursus. Vestibulum eu libero dictum, consequat sem sit amet, fringilla eros. Duis nec nisl nec nibh pellentesque aliquam. Aenean at elit eu dolor malesuada ultrices at sit amet metus. Fusce ac cursus nisl, at luctus ante. Nulla eget dolor id felis varius suscipit vel eu tortor.
        Duis facilisis accumsan mauris, et tincidunt lacus tincidunt id. Mauris ut sodales felis, eget commodo enim. Mauris sed semper mauris, vitae tristique libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus dignissim, orci nec interdum fermentum, lacus lectus tristique mi, ut venenatis magna nisi id justo. Quisque viverra euismod tincidunt. Duis sollicitudin sem risus, eu pellentesque est auctor non. Aenean maximus pellentesque odio nec pulvinar.
        Proin sed porttitor velit. Aenean vulputate consequat ligula, in semper quam vulputate vitae. Quisque pharetra efficitur placerat. Nunc et pulvinar urna. Ut orci leo, fringilla at mauris nec, congue tincidunt elit. Mauris est orci, laoreet non nisl sit amet, egestas suscipit mauris. Praesent quis tempor lectus. Nulla enim leo, malesuada non volutpat vel, bibendum in ex. Suspendisse pulvinar vitae quam eget malesuada.
        Integer sapien tortor, consectetur sit amet nisi quis, pulvinar vulputate magna. Morbi efficitur fermentum finibus. Phasellus a lacus ante. In sit amet nisl quis dui finibus laoreet non at augue. Nunc vulputate volutpat massa varius eleifend. Pellentesque non odio non mi interdum porttitor. Donec quis metus eu erat faucibus vulputate id ut neque. Vestibulum augue mi, ultrices a porta fringilla, volutpat sit amet nisi. Vivamus at tellus nec erat blandit viverra. Nulla et vulputate lorem. Vivamus pulvinar nisl non nisi venenatis, eu molestie erat mattis. Curabitur a nisl faucibus, luctus neque et, malesuada nisl. Donec convallis, sapien non tristique sodales, nibh augue facilisis urna, in eleifend purus tellus ac quam.
        Mauris finibus, enim ac dapibus tempus, augue augue interdum massa, sed mattis felis tortor id velit. Curabitur luctus egestas sem, tempus interdum dui pharetra id. Mauris scelerisque tortor nulla, eget facilisis erat pulvinar vitae. Aenean condimentum commodo libero. Curabitur eleifend massa sagittis nisi malesuada pellentesque. Maecenas metus enim, porta a ornare vitae, porttitor vel quam. Nunc viverra odio eros, eget elementum nibh finibus sit amet. Pellentesque quis fermentum arcu, id tempor velit. Mauris facilisis gravida odio quis euismod. Donec ultricies sed est eget lacinia. Aliquam tincidunt placerat urna sit amet pellentesque.
        Nullam luctus tortor quis tellus venenatis sodales. Donec vel felis eget mi consectetur efficitur. Etiam aliquam nisi sit amet quam interdum, at iaculis urna scelerisque. Vivamus porta neque arcu, nec pretium magna pellentesque nec. Etiam id aliquet urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum, velit non viverra cursus, felis augue posuere neque, nec posuere dui nisi eleifend velit. Phasellus est urna, viverra eget turpis vel, cursus pretium ex. Curabitur mattis convallis velit, vitae auctor purus imperdiet ut. Sed fringilla feugiat augue, ac consectetur lorem tincidunt quis. Vivamus tincidunt dolor ut laoreet pharetra. Aliquam rhoncus vel odio at lobortis.
        Cras faucibus purus non metus aliquam, sed gravida leo feugiat. Curabitur laoreet malesuada volutpat. Vestibulum faucibus nisl eu elit sodales, in blandit ante suscipit. Quisque tincidunt purus nibh, eu efficitur turpis malesuada in. Vivamus aliquet sagittis dolor, non pulvinar nunc sollicitudin at. Sed tincidunt rutrum mauris, vel consectetur lectus condimentum at. Nulla auctor interdum augue, ac facilisis diam rhoncus ut.
        Cras at fringilla mauris. Donec ac condimentum neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut nec mauris id tortor laoreet posuere. Integer mollis dui vel orci pharetra laoreet. Nam quis ligula a lectus pretium rutrum. Donec vel lorem porta ex malesuada volutpat. Etiam venenatis ex molestie, sodales ante quis, tempus urna. Nunc vulputate at ipsum feugiat aliquet. Sed convallis, nunc eu pretium pretium, ante nulla tempor erat, sit amet dignissim risus magna a quam. Donec a ipsum malesuada lectus lacinia varius eget ac dui. Integer risus libero, vulputate eu elit non, tempus iaculis tellus. Curabitur lobortis vel erat sit amet viverra. Integer consequat, odio rhoncus varius aliquet, tortor nisi sodales urna, vel lobortis mi urna sed erat.
        Mauris commodo nisl ac urna aliquam condimentum. Curabitur enim libero, bibendum ut placerat et, aliquam eu tellus. Sed in feugiat tortor. Phasellus lobortis quam a nibh gravida mollis. Donec sit amet odio convallis, pharetra eros et, maximus nisi. Nam pellentesque dolor ut mattis tempor. Nulla vel porta turpis. Proin sed vulputate est. Nulla facilisi. Nullam odio sapien, feugiat non leo nec, cursus sagittis magna. Proin ac velit turpis.`
    );
  }
}
